import keyBy from "lodash.keyby";
import { Tribe, Troop, TroopType } from "../types/CommonTypes";
import { BuildingEnum } from "./building";

const troops: Record<string, Troop> = keyBy([
    {
        "id": "Romans|t1",
        "tribe": Tribe.Romans,
        "troopId": "t1",
        "name": "Legionnaire",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 40,
        "infantryDefense": 35,
        "calvaryDefense": 50,
        "speed": 6,
        "carry": 50,
        "lumber": 120,
        "clay": 100,
        "iron": 150,
        "crop": 30,
        "consumption": 1,
        "trainingTime": 1600
    },
    {
        "id": "Romans|t2",
        "tribe": Tribe.Romans,
        "troopId": "t2",
        "name": "Praetorian",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 30,
        "infantryDefense": 65,
        "calvaryDefense": 35,
        "speed": 5,
        "carry": 20,
        "lumber": 100,
        "clay": 130,
        "iron": 160,
        "crop": 70,
        "consumption": 1,
        "trainingTime": 1760
    },
    {
        "id": "Romans|t3",
        "tribe": Tribe.Romans,
        "troopId": "t3",
        "name": "Imperian",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 70,
        "infantryDefense": 40,
        "calvaryDefense": 25,
        "speed": 7,
        "carry": 50,
        "lumber": 150,
        "clay": 160,
        "iron": 210,
        "crop": 80,
        "consumption": 1,
        "trainingTime": 1920
    },
    {
        "id": "Romans|t4",
        "tribe": Tribe.Romans,
        "troopId": "t4",
        "name": "Equites Legati",
        "type": TroopType.Calvary,
        "isScout": true,
        "attack": 0,
        "infantryDefense": 20,
        "calvaryDefense": 10,
        "speed": 16,
        "carry": 0,
        "lumber": 140,
        "clay": 160,
        "iron": 20,
        "crop": 40,
        "consumption": 2,
        "trainingTime": 1360
    },
    {
        "id": "Romans|t5",
        "tribe": Tribe.Romans,
        "troopId": "t5",
        "name": "Equites Imperatoris",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 120,
        "infantryDefense": 65,
        "calvaryDefense": 50,
        "speed": 14,
        "carry": 100,
        "lumber": 550,
        "clay": 440,
        "iron": 320,
        "crop": 100,
        "consumption": 3,
        "trainingTime": 2640
    },
    {
        "id": "Romans|t6",
        "tribe": Tribe.Romans,
        "troopId": "t6",
        "name": "Equites Caesaris",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 180,
        "infantryDefense": 80,
        "calvaryDefense": 105,
        "speed": 10,
        "carry": 70,
        "lumber": 550,
        "clay": 640,
        "iron": 800,
        "crop": 180,
        "consumption": 4,
        "trainingTime": 3520
    },
    {
        "id": "Romans|t7",
        "tribe": Tribe.Romans,
        "troopId": "t7",
        "name": "Battering ram",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 60,
        "infantryDefense": 30,
        "calvaryDefense": 75,
        "speed": 4,
        "carry": 0,
        "lumber": 900,
        "clay": 360,
        "iron": 500,
        "crop": 70,
        "consumption": 3,
        "trainingTime": 4600
    },
    {
        "id": "Romans|t8",
        "tribe": Tribe.Romans,
        "troopId": "t8",
        "name": "Fire Catapult",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 75,
        "infantryDefense": 60,
        "calvaryDefense": 10,
        "speed": 3,
        "carry": 0,
        "lumber": 950,
        "clay": 1350,
        "iron": 600,
        "crop": 90,
        "consumption": 6,
        "trainingTime": 9000
    },
    {
        "id": "Romans|t9",
        "tribe": Tribe.Romans,
        "troopId": "t9",
        "name": "Senator",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 40,
        "calvaryDefense": 30,
        "speed": 4,
        "carry": 0,
        "lumber": 30750,
        "clay": 27200,
        "iron": 45000,
        "crop": 37500,
        "consumption": 5,
        "trainingTime": 90700
    },
    {
        "id": "Romans|t10",
        "tribe": Tribe.Romans,
        "troopId": "t10",
        "name": "Settler",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 80,
        "calvaryDefense": 80,
        "speed": 5,
        "carry": 3000,
        "lumber": 4600,
        "clay": 4200,
        "iron": 5800,
        "crop": 4400,
        "consumption": 1,
        "trainingTime": 26900
    },
    {
        "id": "Romans|t11",
        "tribe": Tribe.Romans,
        "troopId": "t11",
        "name": TroopType.Hero,
        "type": TroopType.Hero,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 0,
        "calvaryDefense": 0,
        "speed": 0,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 0,
        "trainingTime": 0
    },
    {
        "id": "Teutons|t1",
        "tribe": Tribe.Teutons,
        "troopId": "t1",
        "name": "Maceman",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 40,
        "infantryDefense": 20,
        "calvaryDefense": 5,
        "speed": 7,
        "carry": 60,
        "lumber": 95,
        "clay": 75,
        "iron": 40,
        "crop": 40,
        "consumption": 1,
        "trainingTime": 720
    },
    {
        "id": "Teutons|t2",
        "tribe": Tribe.Teutons,
        "troopId": "t2",
        "name": "Spearman",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 10,
        "infantryDefense": 35,
        "calvaryDefense": 60,
        "speed": 7,
        "carry": 40,
        "lumber": 145,
        "clay": 70,
        "iron": 85,
        "crop": 40,
        "consumption": 1,
        "trainingTime": 1120
    },
    {
        "id": "Teutons|t3",
        "tribe": Tribe.Teutons,
        "troopId": "t3",
        "name": "Axeman",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 60,
        "infantryDefense": 30,
        "calvaryDefense": 30,
        "speed": 6,
        "carry": 50,
        "lumber": 130,
        "clay": 120,
        "iron": 170,
        "crop": 70,
        "consumption": 1,
        "trainingTime": 1200
    },
    {
        "id": "Teutons|t4",
        "tribe": Tribe.Teutons,
        "troopId": "t4",
        "name": "Scout",
        "type": TroopType.Infantry,
        "isScout": true,
        "attack": 0,
        "infantryDefense": 10,
        "calvaryDefense": 5,
        "speed": 9,
        "carry": 0,
        "lumber": 160,
        "clay": 100,
        "iron": 50,
        "crop": 50,
        "consumption": 1,
        "trainingTime": 1120
    },
    {
        "id": "Teutons|t5",
        "tribe": Tribe.Teutons,
        "troopId": "t5",
        "name": "Paladin",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 55,
        "infantryDefense": 100,
        "calvaryDefense": 40,
        "speed": 10,
        "carry": 110,
        "lumber": 370,
        "clay": 270,
        "iron": 290,
        "crop": 75,
        "consumption": 2,
        "trainingTime": 2400
    },
    {
        "id": "Teutons|t6",
        "tribe": Tribe.Teutons,
        "troopId": "t6",
        "name": "Teutonic Knight",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 150,
        "infantryDefense": 50,
        "calvaryDefense": 75,
        "speed": 9,
        "carry": 80,
        "lumber": 450,
        "clay": 515,
        "iron": 480,
        "crop": 80,
        "consumption": 3,
        "trainingTime": 2960
    },
    {
        "id": "Teutons|t7",
        "tribe": Tribe.Teutons,
        "troopId": "t7",
        "name": "Ram",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 65,
        "infantryDefense": 30,
        "calvaryDefense": 80,
        "speed": 4,
        "carry": 0,
        "lumber": 1000,
        "clay": 300,
        "iron": 350,
        "crop": 70,
        "consumption": 3,
        "trainingTime": 4200
    },
    {
        "id": "Teutons|t8",
        "tribe": Tribe.Teutons,
        "troopId": "t8",
        "name": "Catapult",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 60,
        "calvaryDefense": 10,
        "speed": 3,
        "carry": 0,
        "lumber": 900,
        "clay": 1200,
        "iron": 600,
        "crop": 60,
        "consumption": 6,
        "trainingTime": 9000
    },
    {
        "id": "Teutons|t9",
        "tribe": Tribe.Teutons,
        "troopId": "t9",
        "name": "Chief",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 40,
        "infantryDefense": 60,
        "calvaryDefense": 40,
        "speed": 4,
        "carry": 0,
        "lumber": 35500,
        "clay": 26600,
        "iron": 25000,
        "crop": 27200,
        "consumption": 4,
        "trainingTime": 70500
    },
    {
        "id": "Teutons|t10",
        "tribe": Tribe.Teutons,
        "troopId": "t10",
        "name": "Settler",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 10,
        "infantryDefense": 80,
        "calvaryDefense": 80,
        "speed": 5,
        "carry": 3000,
        "lumber": 5800,
        "clay": 4400,
        "iron": 4600,
        "crop": 5200,
        "consumption": 1,
        "trainingTime": 31000
    },
    {
        "id": "Teutons|t11",
        "tribe": Tribe.Teutons,
        "troopId": "t11",
        "name": TroopType.Hero,
        "type": TroopType.Hero,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 0,
        "calvaryDefense": 0,
        "speed": 0,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 0,
        "trainingTime": 0
    },
    {
        "id": "Gauls|t1",
        "tribe": Tribe.Gauls,
        "troopId": "t1",
        "name": "Phalanx",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 15,
        "infantryDefense": 40,
        "calvaryDefense": 50,
        "speed": 7,
        "carry": 35,
        "lumber": 100,
        "clay": 130,
        "iron": 55,
        "crop": 30,
        "consumption": 1,
        "trainingTime": 1040
    },
    {
        "id": "Gauls|t2",
        "tribe": Tribe.Gauls,
        "troopId": "t2",
        "name": "Swordsman",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 65,
        "infantryDefense": 35,
        "calvaryDefense": 20,
        "speed": 6,
        "carry": 45,
        "lumber": 140,
        "clay": 150,
        "iron": 185,
        "crop": 60,
        "consumption": 1,
        "trainingTime": 1440
    },
    {
        "id": "Gauls|t3",
        "tribe": Tribe.Gauls,
        "troopId": "t3",
        "name": "Pathfinder",
        "type": TroopType.Calvary,
        "isScout": true,
        "attack": 0,
        "infantryDefense": 20,
        "calvaryDefense": 10,
        "speed": 17,
        "carry": 0,
        "lumber": 170,
        "clay": 150,
        "iron": 20,
        "crop": 40,
        "consumption": 2,
        "trainingTime": 1360
    },
    {
        "id": "Gauls|t4",
        "tribe": Tribe.Gauls,
        "troopId": "t4",
        "name": "Theutates Thunder",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 100,
        "infantryDefense": 25,
        "calvaryDefense": 40,
        "speed": 19,
        "carry": 75,
        "lumber": 350,
        "clay": 450,
        "iron": 230,
        "crop": 60,
        "consumption": 2,
        "trainingTime": 2480
    },
    {
        "id": "Gauls|t5",
        "tribe": Tribe.Gauls,
        "troopId": "t5",
        "name": "Druidrider",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 45,
        "infantryDefense": 115,
        "calvaryDefense": 55,
        "speed": 16,
        "carry": 35,
        "lumber": 360,
        "clay": 330,
        "iron": 280,
        "crop": 120,
        "consumption": 2,
        "trainingTime": 2560
    },
    {
        "id": "Gauls|t6",
        "tribe": Tribe.Gauls,
        "troopId": "t6",
        "name": "Haeduan",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 140,
        "infantryDefense": 60,
        "calvaryDefense": 165,
        "speed": 13,
        "carry": 65,
        "lumber": 500,
        "clay": 620,
        "iron": 675,
        "crop": 170,
        "consumption": 3,
        "trainingTime": 3120
    },
    {
        "id": "Gauls|t7",
        "tribe": Tribe.Gauls,
        "troopId": "t7",
        "name": "Ram",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 30,
        "calvaryDefense": 105,
        "speed": 4,
        "carry": 0,
        "lumber": 950,
        "clay": 555,
        "iron": 330,
        "crop": 75,
        "consumption": 3,
        "trainingTime": 5000
    },
    {
        "id": "Gauls|t8",
        "tribe": Tribe.Gauls,
        "troopId": "t8",
        "name": "Trebuchet",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 70,
        "infantryDefense": 45,
        "calvaryDefense": 10,
        "speed": 3,
        "carry": 0,
        "lumber": 960,
        "clay": 1450,
        "iron": 630,
        "crop": 90,
        "consumption": 6,
        "trainingTime": 9000
    },
    {
        "id": "Gauls|t9",
        "tribe": Tribe.Gauls,
        "troopId": "t9",
        "name": "Chieftain",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 40,
        "infantryDefense": 50,
        "calvaryDefense": 50,
        "speed": 5,
        "carry": 0,
        "lumber": 30750,
        "clay": 45400,
        "iron": 31000,
        "crop": 37500,
        "consumption": 4,
        "trainingTime": 90700
    },
    {
        "id": "Gauls|t10",
        "tribe": Tribe.Gauls,
        "troopId": "t10",
        "name": "Settler",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 80,
        "calvaryDefense": 80,
        "speed": 5,
        "carry": 3000,
        "lumber": 4400,
        "clay": 5600,
        "iron": 4200,
        "crop": 3900,
        "consumption": 1,
        "trainingTime": 22700
    },
    {
        "id": "Gauls|t11",
        "tribe": Tribe.Gauls,
        "troopId": "t11",
        "name": TroopType.Hero,
        "type": TroopType.Hero,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 0,
        "calvaryDefense": 0,
        "speed": 0,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 0,
        "trainingTime": 0
    },
    {
        "id": "Nature|t1",
        "tribe": Tribe.Nature,
        "troopId": "t1",
        "name": "Rat",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 10,
        "infantryDefense": 25,
        "calvaryDefense": 20,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 100,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Nature|t2",
        "tribe": Tribe.Nature,
        "troopId": "t2",
        "name": "Spider",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 20,
        "infantryDefense": 35,
        "calvaryDefense": 40,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Nature|t3",
        "tribe": Tribe.Nature,
        "troopId": "t3",
        "name": "Serpent",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 60,
        "infantryDefense": 40,
        "calvaryDefense": 60,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Nature|t4",
        "tribe": Tribe.Nature,
        "troopId": "t4",
        "name": "Bat",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 80,
        "infantryDefense": 66,
        "calvaryDefense": 50,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Nature|t5",
        "tribe": Tribe.Nature,
        "troopId": "t5",
        "name": "Wild boar",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 70,
        "calvaryDefense": 33,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 2,
        "trainingTime": 0
    },
    {
        "id": "Nature|t6",
        "tribe": Tribe.Nature,
        "troopId": "t6",
        "name": "Wolf",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 100,
        "infantryDefense": 80,
        "calvaryDefense": 70,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 2,
        "trainingTime": 0
    },
    {
        "id": "Nature|t7",
        "tribe": Tribe.Nature,
        "troopId": "t7",
        "name": "Bear",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 250,
        "infantryDefense": 140,
        "calvaryDefense": 200,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 3,
        "trainingTime": 0
    },
    {
        "id": "Nature|t8",
        "tribe": Tribe.Nature,
        "troopId": "t8",
        "name": "Crocodile",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 450,
        "infantryDefense": 380,
        "calvaryDefense": 240,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 3,
        "trainingTime": 0
    },
    {
        "id": "Nature|t9",
        "tribe": Tribe.Nature,
        "troopId": "t9",
        "name": "Tiger",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 200,
        "infantryDefense": 170,
        "calvaryDefense": 250,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 3,
        "trainingTime": 0
    },
    {
        "id": "Nature|t10",
        "tribe": Tribe.Nature,
        "troopId": "t10",
        "name": "Elephant",
        "type": TroopType.Others,
        "isScout": false,
        "attack": 600,
        "infantryDefense": 440,
        "calvaryDefense": 520,
        "speed": 20,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 5,
        "trainingTime": 0
    },
    {
        "id": "Nature|t11",
        "tribe": Tribe.Nature,
        "troopId": "t11",
        "name": TroopType.Hero,
        "type": TroopType.Hero,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 0,
        "calvaryDefense": 0,
        "speed": 0,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 0,
        "trainingTime": 0
    },
    {
        "id": "Natars|t1",
        "tribe": Tribe.Natars,
        "troopId": "t1",
        "name": "Pikeman",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 20,
        "infantryDefense": 35,
        "calvaryDefense": 50,
        "speed": 6,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Natars|t2",
        "tribe": Tribe.Natars,
        "troopId": "t2",
        "name": "Thorned Warrior",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 65,
        "infantryDefense": 30,
        "calvaryDefense": 10,
        "speed": 7,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Natars|t3",
        "tribe": Tribe.Natars,
        "troopId": "t3",
        "name": "Guardsman",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 100,
        "infantryDefense": 90,
        "calvaryDefense": 75,
        "speed": 6,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Natars|t4",
        "tribe": Tribe.Natars,
        "troopId": "t4",
        "name": "Birds Of Prey",
        "type": TroopType.Calvary,
        "isScout": true,
        "attack": 0,
        "infantryDefense": 10,
        "calvaryDefense": 0,
        "speed": 25,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Natars|t5",
        "tribe": Tribe.Natars,
        "troopId": "t5",
        "name": "Axerider",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 155,
        "infantryDefense": 80,
        "calvaryDefense": 50,
        "speed": 14,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 2,
        "trainingTime": 0
    },
    {
        "id": "Natars|t6",
        "tribe": Tribe.Natars,
        "troopId": "t6",
        "name": "Natarian Knight",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 170,
        "infantryDefense": 140,
        "calvaryDefense": 80,
        "speed": 12,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 3,
        "trainingTime": 0
    },
    {
        "id": "Natars|t7",
        "tribe": Tribe.Natars,
        "troopId": "t7",
        "name": "Warelephant",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 250,
        "infantryDefense": 120,
        "calvaryDefense": 150,
        "speed": 5,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 4,
        "trainingTime": 0
    },
    {
        "id": "Natars|t8",
        "tribe": Tribe.Natars,
        "troopId": "t8",
        "name": "Ballista",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 60,
        "infantryDefense": 45,
        "calvaryDefense": 10,
        "speed": 3,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 5,
        "trainingTime": 0
    },
    {
        "id": "Natars|t9",
        "tribe": Tribe.Natars,
        "troopId": "t9",
        "name": "Natarian Emperor",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 80,
        "infantryDefense": 50,
        "calvaryDefense": 50,
        "speed": 5,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Natars|t10",
        "tribe": Tribe.Natars,
        "troopId": "t10",
        "name": "Settler",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 30,
        "infantryDefense": 40,
        "calvaryDefense": 40,
        "speed": 5,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 1,
        "trainingTime": 0
    },
    {
        "id": "Natars|t11",
        "tribe": Tribe.Natars,
        "troopId": "t11",
        "name": TroopType.Hero,
        "type": TroopType.Hero,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 0,
        "calvaryDefense": 0,
        "speed": 0,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 0,
        "trainingTime": 0
    },
    {
        "id": "Egyptians|t1",
        "tribe": Tribe.Egyptians,
        "troopId": "t1",
        "name": "Slave Militia",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 10,
        "infantryDefense": 30,
        "calvaryDefense": 20,
        "speed": 7,
        "carry": 15,
        "lumber": 45,
        "clay": 60,
        "iron": 30,
        "crop": 15,
        "consumption": 1,
        "trainingTime": 530
    },
    {
        "id": "Egyptians|t2",
        "tribe": Tribe.Egyptians,
        "troopId": "t2",
        "name": "Ash Warden",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 30,
        "infantryDefense": 55,
        "calvaryDefense": 40,
        "speed": 6,
        "carry": 50,
        "lumber": 115,
        "clay": 100,
        "iron": 145,
        "crop": 60,
        "consumption": 1,
        "trainingTime": 1380
    },
    {
        "id": "Egyptians|t3",
        "tribe": Tribe.Egyptians,
        "troopId": "t3",
        "name": "Khopesh Warrior",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 65,
        "infantryDefense": 50,
        "calvaryDefense": 20,
        "speed": 7,
        "carry": 45,
        "lumber": 170,
        "clay": 180,
        "iron": 220,
        "crop": 80,
        "consumption": 1,
        "trainingTime": 1440
    },
    {
        "id": "Egyptians|t4",
        "tribe": Tribe.Egyptians,
        "troopId": "t4",
        "name": "Sopdu Explorer",
        "type": TroopType.Calvary,
        "isScout": true,
        "attack": 0,
        "infantryDefense": 20,
        "calvaryDefense": 10,
        "speed": 16,
        "carry": 0,
        "lumber": 170,
        "clay": 150,
        "iron": 20,
        "crop": 40,
        "consumption": 2,
        "trainingTime": 1360
    },
    {
        "id": "Egyptians|t5",
        "tribe": Tribe.Egyptians,
        "troopId": "t5",
        "name": "Anhur Guard",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 110,
        "calvaryDefense": 50,
        "speed": 15,
        "carry": 50,
        "lumber": 360,
        "clay": 330,
        "iron": 280,
        "crop": 120,
        "consumption": 2,
        "trainingTime": 2560
    },
    {
        "id": "Egyptians|t6",
        "tribe": Tribe.Egyptians,
        "troopId": "t6",
        "name": "Resheph Chariot",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 110,
        "infantryDefense": 120,
        "calvaryDefense": 150,
        "speed": 10,
        "carry": 70,
        "lumber": 450,
        "clay": 560,
        "iron": 610,
        "crop": 180,
        "consumption": 3,
        "trainingTime": 3240
    },
    {
        "id": "Egyptians|t7",
        "tribe": Tribe.Egyptians,
        "troopId": "t7",
        "name": "Ram",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 55,
        "infantryDefense": 30,
        "calvaryDefense": 95,
        "speed": 4,
        "carry": 0,
        "lumber": 995,
        "clay": 575,
        "iron": 340,
        "crop": 80,
        "consumption": 3,
        "trainingTime": 4800
    },
    {
        "id": "Egyptians|t8",
        "tribe": Tribe.Egyptians,
        "troopId": "t8",
        "name": "Stone Catapult",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 65,
        "infantryDefense": 55,
        "calvaryDefense": 10,
        "speed": 3,
        "carry": 0,
        "lumber": 980,
        "clay": 1510,
        "iron": 660,
        "crop": 100,
        "consumption": 6,
        "trainingTime": 9000
    },
    {
        "id": "Egyptians|t9",
        "tribe": Tribe.Egyptians,
        "troopId": "t9",
        "name": "Nomarch",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 40,
        "infantryDefense": 50,
        "calvaryDefense": 50,
        "speed": 4,
        "carry": 0,
        "lumber": 34000,
        "clay": 50000,
        "iron": 34000,
        "crop": 42000,
        "consumption": 4,
        "trainingTime": 90700
    },
    {
        "id": "Egyptians|t10",
        "tribe": Tribe.Egyptians,
        "troopId": "t10",
        "name": "Settler",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 80,
        "calvaryDefense": 80,
        "speed": 5,
        "carry": 3000,
        "lumber": 5040,
        "clay": 6510,
        "iron": 4830,
        "crop": 4620,
        "consumption": 1,
        "trainingTime": 24800
    },
    {
        "id": "Egyptians|t11",
        "tribe": Tribe.Egyptians,
        "troopId": "t11",
        "name": TroopType.Hero,
        "type": TroopType.Hero,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 0,
        "calvaryDefense": 0,
        "speed": 0,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 0,
        "trainingTime": 0
    },
    {
        "id": "Huns|t1",
        "tribe": Tribe.Huns,
        "troopId": "t1",
        "name": "Mercenary",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 35,
        "infantryDefense": 40,
        "calvaryDefense": 30,
        "speed": 6,
        "carry": 50,
        "lumber": 130,
        "clay": 80,
        "iron": 40,
        "crop": 40,
        "consumption": 1,
        "trainingTime": 810
    },
    {
        "id": "Huns|t2",
        "tribe": Tribe.Huns,
        "troopId": "t2",
        "name": "Bowman",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 30,
        "calvaryDefense": 10,
        "speed": 6,
        "carry": 30,
        "lumber": 140,
        "clay": 110,
        "iron": 60,
        "crop": 60,
        "consumption": 1,
        "trainingTime": 1120
    },
    {
        "id": "Huns|t3",
        "tribe": Tribe.Huns,
        "troopId": "t3",
        "name": "Spotter",
        "type": TroopType.Calvary,
        "isScout": true,
        "attack": 0,
        "infantryDefense": 20,
        "calvaryDefense": 10,
        "speed": 19,
        "carry": 0,
        "lumber": 170,
        "clay": 150,
        "iron": 20,
        "crop": 40,
        "consumption": 2,
        "trainingTime": 1360
    },
    {
        "id": "Huns|t4",
        "tribe": Tribe.Huns,
        "troopId": "t4",
        "name": "Steppe Rider",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 120,
        "infantryDefense": 30,
        "calvaryDefense": 15,
        "speed": 16,
        "carry": 75,
        "lumber": 290,
        "clay": 370,
        "iron": 190,
        "crop": 45,
        "consumption": 2,
        "trainingTime": 2400
    },
    {
        "id": "Huns|t5",
        "tribe": Tribe.Huns,
        "troopId": "t5",
        "name": "Marksman",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 110,
        "infantryDefense": 80,
        "calvaryDefense": 70,
        "speed": 15,
        "carry": 105,
        "lumber": 320,
        "clay": 350,
        "iron": 330,
        "crop": 50,
        "consumption": 2,
        "trainingTime": 2480
    },
    {
        "id": "Huns|t6",
        "tribe": Tribe.Huns,
        "troopId": "t6",
        "name": "Marauder",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 180,
        "infantryDefense": 60,
        "calvaryDefense": 40,
        "speed": 14,
        "carry": 80,
        "lumber": 450,
        "clay": 560,
        "iron": 610,
        "crop": 140,
        "consumption": 3,
        "trainingTime": 2990
    },
    {
        "id": "Huns|t7",
        "tribe": Tribe.Huns,
        "troopId": "t7",
        "name": "Ram",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 65,
        "infantryDefense": 30,
        "calvaryDefense": 90,
        "speed": 4,
        "carry": 0,
        "lumber": 1060,
        "clay": 330,
        "iron": 360,
        "crop": 70,
        "consumption": 3,
        "trainingTime": 4400
    },
    {
        "id": "Huns|t8",
        "tribe": Tribe.Huns,
        "troopId": "t8",
        "name": "Catapult",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 45,
        "infantryDefense": 55,
        "calvaryDefense": 10,
        "speed": 3,
        "carry": 0,
        "lumber": 950,
        "clay": 1280,
        "iron": 620,
        "crop": 60,
        "consumption": 6,
        "trainingTime": 9000
    },
    {
        "id": "Huns|t9",
        "tribe": Tribe.Huns,
        "troopId": "t9",
        "name": "Logades",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 40,
        "calvaryDefense": 30,
        "speed": 5,
        "carry": 0,
        "lumber": 37200,
        "clay": 27600,
        "iron": 25200,
        "crop": 27600,
        "consumption": 4,
        "trainingTime": 90700
    },
    {
        "id": "Huns|t10",
        "tribe": Tribe.Huns,
        "troopId": "t10",
        "name": "Settler",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 10,
        "infantryDefense": 80,
        "calvaryDefense": 80,
        "speed": 5,
        "carry": 3000,
        "lumber": 6100,
        "clay": 4600,
        "iron": 4800,
        "crop": 5400,
        "consumption": 1,
        "trainingTime": 28950
    },
    {
        "id": "Huns|t11",
        "tribe": Tribe.Huns,
        "troopId": "t11",
        "name": TroopType.Hero,
        "type": TroopType.Hero,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 0,
        "calvaryDefense": 0,
        "speed": 0,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 0,
        "trainingTime": 0
    },
    {
        "id": "Spartans|t1",
        "tribe": Tribe.Spartans,
        "troopId": "t1",
        "name": "Hoplite",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 35,
        "calvaryDefense": 30,
        "speed": 6,
        "carry": 60,
        "lumber": 110,
        "clay": 185,
        "iron": 110,
        "crop": 35,
        "consumption": 1,
        "trainingTime": 1700
    },
    {
        "id": "Spartans|t2",
        "tribe": Tribe.Spartans,
        "troopId": "t2",
        "name": "Sentinel",
        "type": TroopType.Infantry,
        "isScout": true,
        "attack": 0,
        "infantryDefense": 40,
        "calvaryDefense": 22,
        "speed": 9,
        "carry": 0,
        "lumber": 185,
        "clay": 150,
        "iron": 35,
        "crop": 75,
        "consumption": 1,
        "trainingTime": 1232
    },
    {
        "id": "Spartans|t3",
        "tribe": Tribe.Spartans,
        "troopId": "t3",
        "name": "Shieldsman",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 40,
        "infantryDefense": 85,
        "calvaryDefense": 45,
        "speed": 8,
        "carry": 40,
        "lumber": 145,
        "clay": 95,
        "iron": 245,
        "crop": 45,
        "consumption": 1,
        "trainingTime": 1936
    },
    {
        "id": "Spartans|t4",
        "tribe": Tribe.Spartans,
        "troopId": "t4",
        "name": "Twinsteel Therion",
        "type": TroopType.Infantry,
        "isScout": false,
        "attack": 90,
        "infantryDefense": 55,
        "calvaryDefense": 40,
        "speed": 6,
        "carry": 50,
        "lumber": 130,
        "clay": 200,
        "iron": 400,
        "crop": 65,
        "consumption": 1,
        "trainingTime": 2112
    },
    {
        "id": "Spartans|t5",
        "tribe": Tribe.Spartans,
        "troopId": "t5",
        "name": "Elpida Rider",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 55,
        "infantryDefense": 120,
        "calvaryDefense": 90,
        "speed": 16,
        "carry": 110,
        "lumber": 555,
        "clay": 445,
        "iron": 330,
        "crop": 110,
        "consumption": 2,
        "trainingTime": 2816
    },
    {
        "id": "Spartans|t6",
        "tribe": Tribe.Spartans,
        "troopId": "t6",
        "name": "Corinthian Crusher",
        "type": TroopType.Calvary,
        "isScout": false,
        "attack": 195,
        "infantryDefense": 80,
        "calvaryDefense": 75,
        "speed": 9,
        "carry": 80,
        "lumber": 660,
        "clay": 495,
        "iron": 995,
        "crop": 165,
        "consumption": 3,
        "trainingTime": 3432
    },
    {
        "id": "Spartans|t7",
        "tribe": Tribe.Spartans,
        "troopId": "t7",
        "name": "Ram",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 65,
        "infantryDefense": 30,
        "calvaryDefense": 80,
        "speed": 4,
        "carry": 0,
        "lumber": 525,
        "clay": 260,
        "iron": 790,
        "crop": 130,
        "consumption": 3,
        "trainingTime": 4620
    },
    {
        "id": "Spartans|t8",
        "tribe": Tribe.Spartans,
        "troopId": "t8",
        "name": "Ballista",
        "type": TroopType.Siege,
        "isScout": false,
        "attack": 50,
        "infantryDefense": 60,
        "calvaryDefense": 10,
        "speed": 3,
        "carry": 0,
        "lumber": 550,
        "clay": 1240,
        "iron": 825,
        "crop": 135,
        "consumption": 6,
        "trainingTime": 9900
    },
    {
        "id": "Spartans|t9",
        "tribe": Tribe.Spartans,
        "troopId": "t9",
        "name": "Ephor",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 40,
        "infantryDefense": 60,
        "calvaryDefense": 40,
        "speed": 4,
        "carry": 0,
        "lumber": 33450,
        "clay": 30665,
        "iron": 36240,
        "crop": 13935,
        "consumption": 4,
        "trainingTime": 77550
    },
    {
        "id": "Spartans|t10",
        "tribe": Tribe.Spartans,
        "troopId": "t10",
        "name": "Settler",
        "type": TroopType.Settler,
        "isScout": false,
        "attack": 10,
        "infantryDefense": 80,
        "calvaryDefense": 80,
        "speed": 5,
        "carry": 3000,
        "lumber": 5115,
        "clay": 5580,
        "iron": 6045,
        "crop": 3255,
        "consumption": 1,
        "trainingTime": 34100
    },
    {
        "id": "Spartans|t11",
        "tribe": Tribe.Spartans,
        "troopId": "t11",
        "name": TroopType.Hero,
        "type": TroopType.Hero,
        "isScout": false,
        "attack": 0,
        "infantryDefense": 0,
        "calvaryDefense": 0,
        "speed": 0,
        "carry": 0,
        "lumber": 0,
        "clay": 0,
        "iron": 0,
        "crop": 0,
        "consumption": 0,
        "trainingTime": 0
    }
], 'id')

export const getTroopInfo = (tribe: Tribe, troopId: string): Troop => {
    return troops[`${tribe}|${troopId}`]
}

export const getTroopTrainingBuildingIds = (troop: Troop): string[] => {
    switch (troop.type) {
        case TroopType.Infantry:
            return [BuildingEnum.Barracks, BuildingEnum.GreatBarracks]
        case TroopType.Calvary:
            return [BuildingEnum.Stable, BuildingEnum.GreatStable]
        case TroopType.Siege:
            return [BuildingEnum.Workshop]
        case TroopType.Settler:
            return [BuildingEnum.Residence, BuildingEnum.Palace]
        default:
            return []
    }
}

export const getBuildingTrainableTroops = (tribe: Tribe, building: BuildingEnum) => {
    const troopList = Object.values(troops)
    switch (building) {
        case BuildingEnum.Barracks:
        case BuildingEnum.GreatBarracks:
            return troopList.filter(e => e.tribe === tribe && e.type === TroopType.Infantry)
        case BuildingEnum.Stable:
        case BuildingEnum.GreatStable:
            return troopList.filter(e => e.tribe === tribe && e.type === TroopType.Calvary)
        case BuildingEnum.Workshop:
            return troopList.filter(e => e.tribe === tribe && e.type === TroopType.Siege)
        case BuildingEnum.Residence:
        case BuildingEnum.Palace:
            return troopList.filter(e => e.tribe === tribe && e.type === TroopType.Settler)
        default:
            return []
    }
}